pipeline:
  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make vet
      - make lint
      - coverage all
      - make coverage

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    when:
      status: [ success, failure ]

workspace:
  path: /go/src/github.com/appleboy/gin-jwt

matrix:
  GO_VERSION:
    - 1.6.4
    - 1.7.5
